import { test, expect } from './fixtures.mjs'
async function open(page) {
  await page.addInitScript(() => {
    window.storageCalls = []
    for (const method of ['getItem', 'setItem', 'removeItem']) {
      const original = Storage.prototype[method]
      Storage.prototype[method] = function(...args) { window.storageCalls.push([method, ...args]); return original.apply(this, args) }
    }
  })
  await page.goto('/examples/doca/')
  await page.waitForFunction(() => window.demo?.handle)
  // Yjs/lib0 reads three diagnostic flags at module import, before any editor is mounted.
  await page.evaluate(() => { window.startupStorageCalls = [...window.storageCalls]; window.storageCalls.length = 0 })
}
const projection = page => page.evaluate(() => window.demo.model.getValue())
test('two same-account pages: concurrent native/model edits, own undo, reconnect, readonly, stable handle', async ({ page, context }) => {
  await open(page)
  const second = await context.newPage()
  await second.goto(await page.evaluate(() => window.demo.link)); await second.waitForFunction(() => window.demo?.handle)
  // Native edit pending its debounce while another session produces a remote update.
  await page.evaluate(() => { window.demo.handle.select(['rect-a']); window.demo.handle.updateSelection({ x: 420 }) })
  await second.evaluate(() => window.demo.model.patch('rect-a', { fill: '#ff0000' }))
  await expect.poll(async () => JSON.stringify(await projection(page)) === JSON.stringify(await projection(second))).toBe(true)
  await expect.poll(() => page.evaluate(() => window.demo.model.getValue().scene.children.find(x => x.id === 'rect-a').x)).toBe(420)
  await page.evaluate(() => window.demo.handle.undo())
  await expect.poll(() => second.evaluate(() => window.demo.model.getValue().scene.children.find(x => x.id === 'rect-a').x)).toBe(360)
  expect((await projection(page)).scene.children.find(x => x.id === 'rect-a').fill).toBe('#ff0000')
  await page.evaluate(() => window.demo.changeConnection(false))
  await page.evaluate(() => window.demo.model.patch('rect-a', { y: 220 }))
  await second.evaluate(() => window.demo.model.patch('rect-b', { y: 240 }))
  await page.evaluate(() => window.demo.changeConnection(true))
  await expect.poll(async () => JSON.stringify(await projection(page)) === JSON.stringify(await projection(second))).toBe(true)
  await page.evaluate(() => { window.savedHandle = window.demo.handle; window.savedCanvas = document.querySelector('canvas'); window.demo.setMode('readonly') })
  await expect(page.locator('.canvas-app')).toHaveClass(/is-readonly/)
  const before = await projection(page)
  await page.evaluate(() => { window.demo.handle.addElement({ tag: 'Rect' }); window.demo.handle.removeSelection(); window.demo.handle.replaceAll('hello', 'wrong'); window.demo.setStatus('saving') })
  await page.locator('.canvas-app').focus(); await page.keyboard.press('Delete')
  await page.locator('.canvas-host').dblclick({ position: { x: 200, y: 400 } })
  await expect(page.locator('.leafer-text-editor')).toHaveCount(0)
  expect(await page.evaluate(() => window.demo.handle.getValue().scene.children.length)).toBe(before.scene.children.length)
  expect(await projection(page)).toEqual(before)
  await page.evaluate(() => window.demo.setMode('edit'))
  await expect(page.locator('.canvas-app')).not.toHaveClass(/is-readonly/)
  expect(await page.evaluate(() => window.savedHandle === window.demo.handle && window.savedCanvas === document.querySelector('canvas') && window.demo.readyCount === 1)).toBe(true)
  expect(await page.evaluate(() => window.storageCalls)).toEqual([])
  await second.close()
})
test('same user has distinct session overlays, readonly and blur clear local presence', async ({ page, context }) => {
  await open(page)
  const second = await context.newPage(); await second.goto(await page.evaluate(() => window.demo.link)); await second.waitForFunction(() => window.demo?.handle)
  await page.locator('.canvas-app').focus(); await page.evaluate(() => window.demo.handle.select(['rect-a']))
  await expect(second.locator('[data-remote-session]')).toHaveCount(1)
  expect(await page.evaluate(() => window.demo.identity.userId)).toBe(await second.evaluate(() => window.demo.identity.userId))
  expect(await page.evaluate(() => window.demo.identity.sessionId)).not.toBe(await second.evaluate(() => window.demo.identity.sessionId))
  await second.evaluate(() => window.demo.setMode('readonly')); await expect(second.locator('[data-remote-session]')).toHaveCount(0)
  await page.evaluate(() => window.demo.setMode('readonly')); await second.evaluate(() => window.demo.setMode('edit'))
  await expect(second.locator('[data-remote-session]')).toHaveCount(0)
  await second.close()
})
test('60 seconds idle including select, zoom, scroll, resize: zero content updates/storage', async ({ page }) => {
  await open(page)
  const baseline = await projection(page)
  await page.waitForTimeout(1000)
  expect(await projection(page)).toEqual(baseline)
  await page.evaluate(() => window.demo.handle.select(['rect-a']))
  await page.getByRole('button', { name: '放大', exact: true }).click()
  await page.mouse.wheel(0, 100)
  await page.setViewportSize({ width: 1200, height: 750 })
  await page.waitForTimeout(1000)
  expect(await projection(page)).toEqual(baseline)
  // Real elapsed time: not fake timers.
  await page.waitForTimeout(60000)
  expect(await page.evaluate(() => window.demo.allUpdates.length)).toBe(0)
  expect(await page.evaluate(() => window.storageCalls)).toEqual([])
  expect(await page.evaluate(() => window.demo.readyCount)).toBe(1)
})

test('native group/ungroup, model replaceAll/undo, stable IDs and selection survive peer changes', async ({ page, context }) => {
  await open(page)
  const second = await context.newPage(); await second.goto(await page.evaluate(() => window.demo.link)); await second.waitForFunction(() => window.demo?.handle)
  await page.evaluate(() => { window.demo.handle.select(['rect-a', 'rect-b']); window.demo.handle.groupSelection(); window.demo.handle.flush() })
  await expect.poll(() => second.evaluate(() => window.demo.model.getValue().scene.children.some(x => x.tag === 'Group'))).toBe(true)
  await second.evaluate(() => window.demo.model.patch('rect-a', { fill: '#00ffaa' }))
  await page.evaluate(() => { window.demo.handle.ungroupSelection(); window.demo.handle.flush() })
  await expect.poll(() => page.evaluate(() => window.demo.model.getValue().scene.children.some(x => x.tag === 'Group'))).toBe(false)
  await page.evaluate(() => window.demo.handle.replaceAll('hello', 'Hello!'))
  await expect.poll(() => second.evaluate(() => window.demo.model.find('Hello!').length)).toBe(1)
  await page.evaluate(() => window.demo.handle.undo())
  await expect.poll(() => second.evaluate(() => window.demo.model.find('hello').length)).toBe(1)
  expect((await projection(page)).scene.children.find(x => x.id === 'rect-a').fill).toBe('#00ffaa')
  await second.close()
})
test('asset stable path, upload cancellation on readonly, permission-checked download failure', async ({ page }) => {
  await open(page)
  await page.evaluate(() => { window.demo.resourceControls.hold = true; const c = document.createElement('canvas'); c.width = 40; c.height = 20; window.uploadPromise = new Promise(resolve => c.toBlob(resolve, 'image/png')).then(blob => window.demo.handle.insertImageFile(blob)).catch(() => null) })
  await expect.poll(() => page.evaluate(() => window.demo.resourceLog.filter(x => x.type === 'upload').length)).toBe(1)
  await page.evaluate(() => window.demo.setMode('readonly'))
  await expect(page.locator('.canvas-app')).toHaveClass(/is-readonly/)
  await page.evaluate(() => window.demo.resourceControls.complete())
  expect(await page.evaluate(() => window.uploadPromise)).toBe(null)
  expect(await page.evaluate(() => window.demo.resourceLog[0].signal.aborted)).toBe(true)
  expect((await projection(page)).scene.children).toHaveLength(3)
  await page.evaluate(() => window.demo.setMode('edit'))
  await expect(page.locator('.canvas-app')).not.toHaveClass(/is-readonly/)
  const image = await page.evaluate(() => window.demo.handle.addImage('stable-asset-id'))
  expect(image).not.toBeNull()
  await page.evaluate(() => window.demo.handle.flush())
  const saved = await projection(page)
  expect(saved.scene.children.find(x => x.tag === 'Image').url).toBe('stable-asset-id')
  expect(JSON.stringify(saved)).not.toContain('data:image')
  await page.evaluate(() => window.demo.resourceControls.denyDownload = true)
  await page.getByRole('button', { name: '下载图片', exact: true }).click()
  await expect.poll(() => page.evaluate(() => window.demo.errors.some(e => e.includes('DOWNLOAD_DENIED')))).toBe(true)
  expect(await page.evaluate(() => window.demo.resourceLog.filter(x => x.type === 'download').length)).toBe(1)
  // Backend-produced Image nodes need not carry the editor's historical name='image'.
  await page.evaluate(() => window.demo.model.add({ id: 'backend-image', tag: 'Image', width: 40, height: 40, data: { resourcePath: 'backend-asset' } }))
  await expect.poll(() => page.evaluate(() => window.demo.resourceLog.some(x => x.type === 'display' && x.path === 'backend-asset'))).toBe(true)
  expect(JSON.stringify(await projection(page))).not.toContain('data:image')
})
